name: Java CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    strategy:
      matrix:
        java: [ '17', '8' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Covid-remaining-${{ matrix.java }}
        path: app/build/libs/shadow-*.jar
